### PR TITLE
Rename most methods and some functions following a more canonical naming practice

### PR DESCRIPTION
**Pull request by charlestonchas**
Overall approach (some comments in *README_NAMES*):
- adds a little python script *names.py* which has functions to assist in the various tasks
- uses regular expression for finding class and method names in *.py* and *.pyx* files
- class names removed from consideration (they're OK already)
- both C++ and python names changed to the same name
- *names.py* uses subprocess.Popen to run *find* which executes an in-place *sed* for each substitution
- names changed in all *.py* *.pyx* *.h* *.cpp* files 
- all renames (oldname newname) are in file **NAMES_TXN**

**Note:** that **Print()** is not changed, nor **rigidXMat44()**, which will require manual intervention. I'll add issues for these.

**Note:** Only method names were renamed in this branch. Many attribute names are still in camelCase and will require attention for consistency (see Issue #50)

### CODE REVIEW

**Comment by benoistlaurent** [comment]
1. Is it intentional that you modified variables inside C++ functions?

As a example, take a look at `Tests/cpp/cxxtest/ErrorFormatter.h::`.
In the function `dumpBuffer`, there is a variable called `dumpSize` which has been renamed to `dumpsize`.

Doesn't seem very important to me, though.

2. Some test classes are not renamed adequately.
Example: in `Tests/functional/test_reduce.py`  `TestReduceAttract1` has been renamed to `TestreduceAttract1`. The initial name was correct.
It's the same for `TestReduceAttract2` and `TestReduceScorpion`.
The same again for `TestTranslate` in ` Tests/functional/test_translate.py`

3. `forcefield.AddLigand` should have been renamed to `forcefield.add_ligand`
Same goes `ForceField` subclasses.

4. In `Tests/test_misc.py`, the test methods should have been renamed according to PEP8, i.e. with words separated by underscores.

5. Same as 4. for `Tests/test_rigidbody.py::TestRigidbody`

**Comment by charlestonchas** [comment]
For point **3**: Oops. Will fix.

For the other points, these inconsistencies result from choices made for this operation:
1. Re-naming on the order of 100 identifiers in more than 150 .cpp, .h, .py, and .pyx files without manually changing each one, which would have taken much more time for me.
1. Using automatic search and replace of the name string itself, which produced some modifications inside other words. This was why I said I wasn't going to worry about any resulting naming inconsistencies in the C++ code, whose future is not assured anyway.
1. Targeting the user interface by explicitly excluded test function names. I can add these today if that's desirable.

**Comment by benoistlaurent** [comment]
My point is not to say that you should make better scripts: they did a great job.
But maybe correct by hand the few points I highlighted?

**Comment by charlestonchas** [comment]
I wasn't going to modify the utility script, just run it on the test file methods alone since there are quite a few.
BTW I'll continue to ignore any incidental C++ changes unless you see a bunch.

**Comment by charlestonchas** [comment]
Changed the test method names to match the style of the others.
**Ready for merge** (in principle)

**Pull request merged**
